/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.apis

import io.ktor.client.request.request
import jp.co.yumemi.android.code_check.data.models.*
import jp.co.yumemi.android.code_check.remote.core.HttpClientProvider
import io.ktor.client.request.parameter
import io.ktor.http.HttpMethod

interface RateLimitApi {
    /**
    * Get rate limit status for the authenticated user
    *
    * **Note:** Accessing this endpoint does not count against your REST API rate limit.  **Note:** The &#x60;rate&#x60; object is deprecated. If you&#39;re writing new API client code or updating existing code, you should use the &#x60;core&#x60; object instead of the &#x60;rate&#x60; object. The &#x60;core&#x60; object contains the same information that is present in the &#x60;rate&#x60; object.
    *
    * @return RateMinusLimitMinusOverviewModel
    */
    suspend fun rateLimitGet(accessToken: String? = null): RateMinusLimitMinusOverviewModel

}

class HttpClientRateLimitApi(private val httpClientProvider: HttpClientProvider) : RateLimitApi {
    internal val httpClient = httpClientProvider.provide()

    override suspend fun rateLimitGet(accessToken: String?): RateMinusLimitMinusOverviewModel {
        val path = "/rate_limit"

        return httpClient.request {
            url { encodedPath = path }
            method = HttpMethod.Get
        }
    }

}
