/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.ActionsMinusDefaultMinusWorkflowMinusPermissionsModel

import kotlinx.serialization.*

/**
 * 
 * @param defaultWorkflowPermissions 
 * @param canApprovePullRequestReviews Whether GitHub Actions can submit approving pull request reviews.
 */
@Serializable
data class ActionsMinusSetMinusDefaultMinusWorkflowMinusPermissionsModel(
    @Contextual @SerialName(value = "default_workflow_permissions")
    val defaultWorkflowPermissions: ActionsMinusDefaultMinusWorkflowMinusPermissionsModel? = null,
    /* Whether GitHub Actions can submit approving pull request reviews. */
    @SerialName(value = "can_approve_pull_request_reviews")
    val canApprovePullRequestReviews: kotlin.Boolean? = null
) {

}

