/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.AdvancedMinusSecurityMinusActiveMinusCommittersMinusUserModel

import kotlinx.serialization.*

/**
 * 
 * @param name 
 * @param advancedSecurityCommitters 
 * @param advancedSecurityCommittersBreakdown 
 */
@Serializable
data class AdvancedMinusSecurityMinusActiveMinusCommittersMinusRepositoryModel(
    @SerialName(value = "name")
    val name: kotlin.String,
    @SerialName(value = "advanced_security_committers")
    val advancedSecurityCommitters: kotlin.Int,
    @SerialName(value = "advanced_security_committers_breakdown")
    val advancedSecurityCommittersBreakdown: kotlin.collections.List<AdvancedMinusSecurityMinusActiveMinusCommittersMinusUserModel>
) {

}

