/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.AdvancedMinusSecurityMinusActiveMinusCommittersMinusRepositoryModel

import kotlinx.serialization.*

/**
 * 
 * @param repositories 
 * @param totalAdvancedSecurityCommitters 
 */
@Serializable
data class AdvancedMinusSecurityMinusActiveMinusCommittersModel(
    @SerialName(value = "repositories")
    val repositories: kotlin.collections.List<AdvancedMinusSecurityMinusActiveMinusCommittersMinusRepositoryModel>,
    @SerialName(value = "total_advanced_security_committers")
    val totalAdvancedSecurityCommitters: kotlin.Int? = null
) {

}

