/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models


import kotlinx.serialization.*

/**
 * 
 * @param id 
 * @param nodeId 
 * @param url 
 * @param htmlUrl 
 * @param name 
 * @param slug 
 * @param description 
 * @param privacy 
 * @param permission 
 * @param membersUrl 
 * @param repositoriesUrl 
 * @param parent 
 */
@Serializable
data class BranchRestrictionPolicyTeamsModel(
    @SerialName(value = "id")
    val id: kotlin.Int? = null,
    @SerialName(value = "node_id")
    val nodeId: kotlin.String? = null,
    @SerialName(value = "url")
    val url: kotlin.String? = null,
    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String? = null,
    @SerialName(value = "name")
    val name: kotlin.String? = null,
    @SerialName(value = "slug")
    val slug: kotlin.String? = null,
    @SerialName(value = "description")
    val description: kotlin.String? = null,
    @SerialName(value = "privacy")
    val privacy: kotlin.String? = null,
    @SerialName(value = "permission")
    val permission: kotlin.String? = null,
    @SerialName(value = "members_url")
    val membersUrl: kotlin.String? = null,
    @SerialName(value = "repositories_url")
    val repositoriesUrl: kotlin.String? = null,
    @SerialName(value = "parent")
    val parent: kotlin.String? = null
) {

}

