/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models


import kotlinx.serialization.*

/**
 * Describe a region within a file for the alert.
 * @param path 
 * @param startLine 
 * @param endLine 
 * @param startColumn 
 * @param endColumn 
 */
@Serializable
data class CodeMinusScanningMinusAlertMinusLocationModel(
    @SerialName(value = "path")
    val path: kotlin.String? = null,
    @SerialName(value = "start_line")
    val startLine: kotlin.Int? = null,
    @SerialName(value = "end_line")
    val endLine: kotlin.Int? = null,
    @SerialName(value = "start_column")
    val startColumn: kotlin.Int? = null,
    @SerialName(value = "end_column")
    val endColumn: kotlin.Int? = null
) {

}

