/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.MinimalMinusRepositoryModel
import jp.co.yumemi.android.code_check.data.models.SimpleMinusCommitMinusStatusModel

import kotlinx.serialization.*

/**
 * Combined Commit Status
 * @param state 
 * @param statuses 
 * @param sha 
 * @param totalCount 
 * @param repository 
 * @param commitUrl 
 * @param url 
 */
@Serializable
data class CombinedMinusCommitMinusStatusModel(
    @SerialName(value = "state")
    val state: kotlin.String,
    @SerialName(value = "statuses")
    val statuses: kotlin.collections.List<SimpleMinusCommitMinusStatusModel>,
    @SerialName(value = "sha")
    val sha: kotlin.String,
    @SerialName(value = "total_count")
    val totalCount: kotlin.Int,
    @SerialName(value = "repository")
    val repository: MinimalMinusRepositoryModel,
    @SerialName(value = "commit_url")
    val commitUrl: kotlin.String,
    @SerialName(value = "url")
    val url: kotlin.String
) {

}

