/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.CommitSearchResultItemCommitAuthorModel
import jp.co.yumemi.android.code_check.data.models.NullableMinusGitMinusUserModel
import jp.co.yumemi.android.code_check.data.models.ShortBranchCommitModel
import jp.co.yumemi.android.code_check.data.models.VerificationModel

import kotlinx.serialization.*

/**
 * 
 * @param author 
 * @param committer 
 * @param commentCount 
 * @param message 
 * @param tree 
 * @param url 
 * @param verification 
 */
@Serializable
data class CommitSearchResultItemCommitModel(
    @SerialName(value = "author")
    val author: CommitSearchResultItemCommitAuthorModel,
    @SerialName(value = "committer")
    val committer: NullableMinusGitMinusUserModel?,
    @SerialName(value = "comment_count")
    val commentCount: kotlin.Int,
    @SerialName(value = "message")
    val message: kotlin.String,
    @SerialName(value = "tree")
    val tree: ShortBranchCommitModel,
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "verification")
    val verification: VerificationModel? = null
) {

}

