/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.NullableMinusCodeMinusOfMinusConductMinusSimpleModel
import jp.co.yumemi.android.code_check.data.models.NullableMinusCommunityMinusHealthMinusFileModel
import jp.co.yumemi.android.code_check.data.models.NullableMinusLicenseMinusSimpleModel

import kotlinx.serialization.*

/**
 * 
 * @param codeOfConduct 
 * @param codeOfConductFile 
 * @param license 
 * @param contributing 
 * @param readme 
 * @param issueTemplate 
 * @param pullRequestTemplate 
 */
@Serializable
data class CommunityProfileFilesModel(
    @SerialName(value = "code_of_conduct")
    val codeOfConduct: NullableMinusCodeMinusOfMinusConductMinusSimpleModel?,
    @SerialName(value = "code_of_conduct_file")
    val codeOfConductFile: NullableMinusCommunityMinusHealthMinusFileModel?,
    @SerialName(value = "license")
    val license: NullableMinusLicenseMinusSimpleModel?,
    @SerialName(value = "contributing")
    val contributing: NullableMinusCommunityMinusHealthMinusFileModel?,
    @SerialName(value = "readme")
    val readme: NullableMinusCommunityMinusHealthMinusFileModel?,
    @SerialName(value = "issue_template")
    val issueTemplate: NullableMinusCommunityMinusHealthMinusFileModel?,
    @SerialName(value = "pull_request_template")
    val pullRequestTemplate: NullableMinusCommunityMinusHealthMinusFileModel?
) {

}

