/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.CommunityProfileFilesModel

import kotlinx.serialization.*

/**
 * Community Profile
 * @param healthPercentage 
 * @param description 
 * @param documentation 
 * @param files 
 * @param updatedAt 
 * @param contentReportsEnabled 
 */
@Serializable
data class CommunityMinusProfileModel(
    @SerialName(value = "health_percentage")
    val healthPercentage: kotlin.Int,
    @SerialName(value = "description")
    val description: kotlin.String?,
    @SerialName(value = "documentation")
    val documentation: kotlin.String?,
    @SerialName(value = "files")
    val files: CommunityProfileFilesModel,
    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String?,
    @SerialName(value = "content_reports_enabled")
    val contentReportsEnabled: kotlin.Boolean? = null
) {

}

