/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.ContributorActivityWeeksModel
import jp.co.yumemi.android.code_check.data.models.NullableMinusSimpleMinusUserModel

import kotlinx.serialization.*

/**
 * Contributor Activity
 * @param author 
 * @param total 
 * @param weeks 
 */
@Serializable
data class ContributorMinusActivityModel(
    @SerialName(value = "author")
    val author: NullableMinusSimpleMinusUserModel?,
    @SerialName(value = "total")
    val total: kotlin.Int,
    @SerialName(value = "weeks")
    val weeks: kotlin.collections.List<ContributorActivityWeeksModel>
) {

}

