/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.ContentTreeLinksModel

import kotlinx.serialization.*

/**
 * An object describing a symlink
 * @param type 
 * @param submoduleGitUrl 
 * @param propertySize 
 * @param name 
 * @param path 
 * @param sha 
 * @param url 
 * @param gitUrl 
 * @param htmlUrl 
 * @param downloadUrl 
 * @param links 
 */
@Serializable
data class ContentMinusSubmoduleModel(
    @SerialName(value = "type")
    val type: kotlin.String,
    @SerialName(value = "submodule_git_url")
    val submoduleGitUrl: kotlin.String,
    @SerialName(value = "size")
    val propertySize: kotlin.Int,
    @SerialName(value = "name")
    val name: kotlin.String,
    @SerialName(value = "path")
    val path: kotlin.String,
    @SerialName(value = "sha")
    val sha: kotlin.String,
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "git_url")
    val gitUrl: kotlin.String?,
    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String?,
    @SerialName(value = "download_url")
    val downloadUrl: kotlin.String?,
    @SerialName(value = "_links")
    val links: ContentTreeLinksModel
) {

}

