/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models


import kotlinx.serialization.*

/**
 * 
 * @param groupId The internal ID of the group
 * @param groupName The display name of the group
 * @param updatedAt The time of the last update for this group
 */
@Serializable
data class ExternalGroupsGroupsModel(
    /* The internal ID of the group */
    @SerialName(value = "group_id")
    val groupId: kotlin.Int,
    /* The display name of the group */
    @SerialName(value = "group_name")
    val groupName: kotlin.String,
    /* The time of the last update for this group */
    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String
) {

}

