/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.GistMinusHistoryModel
import jp.co.yumemi.android.code_check.data.models.GistModel
import jp.co.yumemi.android.code_check.data.models.GistSimpleFilesModel
import jp.co.yumemi.android.code_check.data.models.GistSimpleForksModel
import jp.co.yumemi.android.code_check.data.models.SimpleMinusUserModel

import kotlinx.serialization.*

/**
 * Gist Simple
 * @param forks 
 * @param history 
 * @param forkOf 
 * @param url 
 * @param forksUrl 
 * @param commitsUrl 
 * @param id 
 * @param nodeId 
 * @param gitPullUrl 
 * @param gitPushUrl 
 * @param htmlUrl 
 * @param files 
 * @param isPublic 
 * @param createdAt 
 * @param updatedAt 
 * @param description 
 * @param comments 
 * @param user 
 * @param commentsUrl 
 * @param owner 
 * @param truncated 
 */
@Serializable
data class GistMinusSimpleModel(
    @SerialName(value = "forks")
    @Deprecated(message = "This property is deprecated.")
    val forks: kotlin.collections.List<GistSimpleForksModel>? = null,
    @SerialName(value = "history")
    @Deprecated(message = "This property is deprecated.")
    val history: kotlin.collections.List<GistMinusHistoryModel>? = null,
    @SerialName(value = "fork_of")
    val forkOf: GistModel? = null,
    @SerialName(value = "url")
    val url: kotlin.String? = null,
    @SerialName(value = "forks_url")
    val forksUrl: kotlin.String? = null,
    @SerialName(value = "commits_url")
    val commitsUrl: kotlin.String? = null,
    @SerialName(value = "id")
    val id: kotlin.String? = null,
    @SerialName(value = "node_id")
    val nodeId: kotlin.String? = null,
    @SerialName(value = "git_pull_url")
    val gitPullUrl: kotlin.String? = null,
    @SerialName(value = "git_push_url")
    val gitPushUrl: kotlin.String? = null,
    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String? = null,
    @Contextual @SerialName(value = "files")
    val files: kotlin.collections.Map<kotlin.String, GistSimpleFilesModel>? = null,
    @SerialName(value = "is_public")
    val isPublic: kotlin.Boolean? = null,
    @SerialName(value = "created_at")
    val createdAt: kotlin.String? = null,
    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String? = null,
    @SerialName(value = "description")
    val description: kotlin.String? = null,
    @SerialName(value = "comments")
    val comments: kotlin.Int? = null,
    @SerialName(value = "user")
    val user: kotlin.String? = null,
    @SerialName(value = "comments_url")
    val commentsUrl: kotlin.String? = null,
    @SerialName(value = "owner")
    val owner: SimpleMinusUserModel? = null,
    @SerialName(value = "truncated")
    val truncated: kotlin.Boolean? = null
) {

}

