/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.AppMinusPermissionsModel

import kotlinx.serialization.*

/**
 * 
 * @param accessToken The OAuth access token used to authenticate to the GitHub API.
 * @param target The name of the user or organization to scope the user-to-server access token to. **Required** unless `target_id` is specified.
 * @param targetId The ID of the user or organization to scope the user-to-server access token to. **Required** unless `target` is specified.
 * @param repositories The list of repository names to scope the user-to-server access token to. `repositories` may not be specified if `repository_ids` is specified.
 * @param repositoryIds The list of repository IDs to scope the user-to-server access token to. `repository_ids` may not be specified if `repositories` is specified.
 * @param permissions 
 */
@Serializable
data class InlineObject6Model(
    /* The OAuth access token used to authenticate to the GitHub API. */
    @SerialName(value = "access_token")
    val accessToken: kotlin.String,
    /* The name of the user or organization to scope the user-to-server access token to. **Required** unless `target_id` is specified. */
    @SerialName(value = "target")
    val target: kotlin.String? = null,
    /* The ID of the user or organization to scope the user-to-server access token to. **Required** unless `target` is specified. */
    @SerialName(value = "target_id")
    val targetId: kotlin.Int? = null,
    /* The list of repository names to scope the user-to-server access token to. `repositories` may not be specified if `repository_ids` is specified. */
    @SerialName(value = "repositories")
    val repositories: kotlin.collections.List<kotlin.String>? = null,
    /* The list of repository IDs to scope the user-to-server access token to. `repository_ids` may not be specified if `repositories` is specified. */
    @SerialName(value = "repository_ids")
    val repositoryIds: kotlin.collections.List<kotlin.Int>? = null,
    @SerialName(value = "permissions")
    val permissions: AppMinusPermissionsModel? = null
) {

}

