/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.AppMinusPermissionsModel

import kotlinx.serialization.*

/**
 * 
 * @param repositories List of repository names that the token should have access to
 * @param repositoryIds List of repository IDs that the token should have access to
 * @param permissions 
 */
@Serializable
data class InlineObject1Model(
    /* List of repository names that the token should have access to */
    @SerialName(value = "repositories")
    val repositories: kotlin.collections.List<kotlin.String>? = null,
    /* List of repository IDs that the token should have access to */
    @SerialName(value = "repository_ids")
    val repositoryIds: kotlin.collections.List<kotlin.Int>? = null,
    @SerialName(value = "permissions")
    val permissions: AppMinusPermissionsModel? = null
) {

}

