/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models


import kotlinx.serialization.*

/**
 * 
 * @param subscribed Determines if notifications should be received from this repository.
 * @param ignored Determines if all notifications should be blocked from this repository.
 */
@Serializable
data class InlineObject137Model(
    /* Determines if notifications should be received from this repository. */
    @SerialName(value = "subscribed")
    val subscribed: kotlin.Boolean? = null,
    /* Determines if all notifications should be blocked from this repository. */
    @SerialName(value = "ignored")
    val ignored: kotlin.Boolean? = null
) {

}

