/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.NullableSimpleCommitAuthorModel

import kotlinx.serialization.*

/**
 * Simple Commit
 * @param id 
 * @param treeId 
 * @param message 
 * @param timestamp 
 * @param author 
 * @param committer 
 */
@Serializable
data class NullableMinusSimpleMinusCommitModel(
    @SerialName(value = "id")
    val id: kotlin.String,
    @SerialName(value = "tree_id")
    val treeId: kotlin.String,
    @SerialName(value = "message")
    val message: kotlin.String,
    @SerialName(value = "timestamp")
    val timestamp: kotlin.String,
    @SerialName(value = "author")
    val author: NullableSimpleCommitAuthorModel?,
    @SerialName(value = "committer")
    val committer: NullableSimpleCommitAuthorModel?
) {

}

