/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.ProtectedBranchRequiredPullRequestReviewsBypassPullRequestAllowancesModel
import jp.co.yumemi.android.code_check.data.models.ProtectedBranchRequiredPullRequestReviewsDismissalRestrictionsModel

import kotlinx.serialization.*

/**
 * 
 * @param url 
 * @param dismissStaleReviews 
 * @param requireCodeOwnerReviews 
 * @param requiredApprovingReviewCount 
 * @param dismissalRestrictions 
 * @param bypassPullRequestAllowances 
 */
@Serializable
data class ProtectedBranchRequiredPullRequestReviewsModel(
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "dismiss_stale_reviews")
    val dismissStaleReviews: kotlin.Boolean? = null,
    @SerialName(value = "require_code_owner_reviews")
    val requireCodeOwnerReviews: kotlin.Boolean? = null,
    @SerialName(value = "required_approving_review_count")
    val requiredApprovingReviewCount: kotlin.Int? = null,
    @SerialName(value = "dismissal_restrictions")
    val dismissalRestrictions: ProtectedBranchRequiredPullRequestReviewsDismissalRestrictionsModel? = null,
    @SerialName(value = "bypass_pull_request_allowances")
    val bypassPullRequestAllowances: ProtectedBranchRequiredPullRequestReviewsBypassPullRequestAllowancesModel? = null
) {

}

