/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.BranchMinusRestrictionMinusPolicyModel
import jp.co.yumemi.android.code_check.data.models.BranchProtectionRequiredLinearHistoryModel
import jp.co.yumemi.android.code_check.data.models.BranchProtectionRequiredSignaturesModel
import jp.co.yumemi.android.code_check.data.models.ProtectedBranchEnforceAdminsModel
import jp.co.yumemi.android.code_check.data.models.ProtectedBranchRequiredLinearHistoryModel
import jp.co.yumemi.android.code_check.data.models.ProtectedBranchRequiredPullRequestReviewsModel
import jp.co.yumemi.android.code_check.data.models.StatusMinusCheckMinusPolicyModel

import kotlinx.serialization.*

/**
 * Branch protections protect branches
 * @param url 
 * @param requiredStatusChecks 
 * @param requiredPullRequestReviews 
 * @param requiredSignatures 
 * @param enforceAdmins 
 * @param requiredLinearHistory 
 * @param allowForcePushes 
 * @param allowDeletions 
 * @param restrictions 
 * @param requiredConversationResolution 
 */
@Serializable
data class ProtectedMinusBranchModel(
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "required_status_checks")
    val requiredStatusChecks: StatusMinusCheckMinusPolicyModel? = null,
    @SerialName(value = "required_pull_request_reviews")
    val requiredPullRequestReviews: ProtectedBranchRequiredPullRequestReviewsModel? = null,
    @SerialName(value = "required_signatures")
    val requiredSignatures: BranchProtectionRequiredSignaturesModel? = null,
    @SerialName(value = "enforce_admins")
    val enforceAdmins: ProtectedBranchEnforceAdminsModel? = null,
    @SerialName(value = "required_linear_history")
    val requiredLinearHistory: ProtectedBranchRequiredLinearHistoryModel? = null,
    @SerialName(value = "allow_force_pushes")
    val allowForcePushes: ProtectedBranchRequiredLinearHistoryModel? = null,
    @SerialName(value = "allow_deletions")
    val allowDeletions: ProtectedBranchRequiredLinearHistoryModel? = null,
    @SerialName(value = "restrictions")
    val restrictions: BranchMinusRestrictionMinusPolicyModel? = null,
    @SerialName(value = "required_conversation_resolution")
    val requiredConversationResolution: BranchProtectionRequiredLinearHistoryModel? = null
) {

}

