/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.AuthorAssociationModel
import jp.co.yumemi.android.code_check.data.models.AutoMergeModel
import jp.co.yumemi.android.code_check.data.models.NullableMinusMilestoneModel
import jp.co.yumemi.android.code_check.data.models.NullableMinusSimpleMinusUserModel
import jp.co.yumemi.android.code_check.data.models.PullRequestSimpleHeadModel
import jp.co.yumemi.android.code_check.data.models.PullRequestSimpleLabelsModel
import jp.co.yumemi.android.code_check.data.models.PullRequestSimpleLinksModel
import jp.co.yumemi.android.code_check.data.models.SimpleMinusUserModel
import jp.co.yumemi.android.code_check.data.models.TeamModel

import kotlinx.serialization.*

/**
 * Pull Request Simple
 * @param url 
 * @param id 
 * @param nodeId 
 * @param htmlUrl 
 * @param diffUrl 
 * @param patchUrl 
 * @param issueUrl 
 * @param commitsUrl 
 * @param reviewCommentsUrl 
 * @param reviewCommentUrl 
 * @param commentsUrl 
 * @param statusesUrl 
 * @param number 
 * @param state 
 * @param locked 
 * @param title 
 * @param user 
 * @param body 
 * @param labels 
 * @param milestone 
 * @param createdAt 
 * @param updatedAt 
 * @param closedAt 
 * @param mergedAt 
 * @param mergeCommitSha 
 * @param assignee 
 * @param head 
 * @param base 
 * @param links 
 * @param authorAssociation 
 * @param autoMerge 
 * @param activeLockReason 
 * @param assignees 
 * @param requestedReviewers 
 * @param requestedTeams 
 * @param draft Indicates whether or not the pull request is a draft.
 */
@Serializable
data class PullMinusRequestMinusSimpleModel(
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "id")
    val id: kotlin.Int,
    @SerialName(value = "node_id")
    val nodeId: kotlin.String,
    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String,
    @SerialName(value = "diff_url")
    val diffUrl: kotlin.String,
    @SerialName(value = "patch_url")
    val patchUrl: kotlin.String,
    @SerialName(value = "issue_url")
    val issueUrl: kotlin.String,
    @SerialName(value = "commits_url")
    val commitsUrl: kotlin.String,
    @SerialName(value = "review_comments_url")
    val reviewCommentsUrl: kotlin.String,
    @SerialName(value = "review_comment_url")
    val reviewCommentUrl: kotlin.String,
    @SerialName(value = "comments_url")
    val commentsUrl: kotlin.String,
    @SerialName(value = "statuses_url")
    val statusesUrl: kotlin.String,
    @SerialName(value = "number")
    val number: kotlin.Int,
    @SerialName(value = "state")
    val state: kotlin.String,
    @SerialName(value = "locked")
    val locked: kotlin.Boolean,
    @SerialName(value = "title")
    val title: kotlin.String,
    @SerialName(value = "user")
    val user: NullableMinusSimpleMinusUserModel?,
    @SerialName(value = "body")
    val body: kotlin.String?,
    @SerialName(value = "labels")
    val labels: kotlin.collections.List<PullRequestSimpleLabelsModel>,
    @SerialName(value = "milestone")
    val milestone: NullableMinusMilestoneModel?,
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,
    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String,
    @SerialName(value = "closed_at")
    val closedAt: kotlin.String?,
    @SerialName(value = "merged_at")
    val mergedAt: kotlin.String?,
    @SerialName(value = "merge_commit_sha")
    val mergeCommitSha: kotlin.String?,
    @SerialName(value = "assignee")
    val assignee: NullableMinusSimpleMinusUserModel?,
    @SerialName(value = "head")
    val head: PullRequestSimpleHeadModel,
    @SerialName(value = "base")
    val base: PullRequestSimpleHeadModel,
    @SerialName(value = "_links")
    val links: PullRequestSimpleLinksModel,
    @Contextual @SerialName(value = "author_association")
    val authorAssociation: AuthorAssociationModel,
    @SerialName(value = "auto_merge")
    val autoMerge: AutoMergeModel?,
    @SerialName(value = "active_lock_reason")
    val activeLockReason: kotlin.String? = null,
    @SerialName(value = "assignees")
    val assignees: kotlin.collections.List<SimpleMinusUserModel>? = null,
    @SerialName(value = "requested_reviewers")
    val requestedReviewers: kotlin.collections.List<SimpleMinusUserModel>? = null,
    @SerialName(value = "requested_teams")
    val requestedTeams: kotlin.collections.List<TeamModel>? = null,
    /* Indicates whether or not the pull request is a draft. */
    @SerialName(value = "draft")
    val draft: kotlin.Boolean? = null
) {

}

