/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models


import kotlinx.serialization.*

/**
 * Restrict who can push to the protected branch. User, app, and team `restrictions` are only available for organization-owned repositories. Set to `null` to disable.
 * @param users The list of user `login`s with push access
 * @param teams The list of team `slug`s with push access
 * @param apps The list of app `slug`s with push access
 */
@Serializable
data class ReposOwnerRepoBranchesBranchProtectionRestrictionsModel(
    /* The list of user `login`s with push access */
    @SerialName(value = "users")
    val users: kotlin.collections.List<kotlin.String>,
    /* The list of team `slug`s with push access */
    @SerialName(value = "teams")
    val teams: kotlin.collections.List<kotlin.String>,
    /* The list of app `slug`s with push access */
    @SerialName(value = "apps")
    val apps: kotlin.collections.List<kotlin.String>? = null
) {

}

