/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.ScimGroupListEnterpriseMembersModel
import jp.co.yumemi.android.code_check.data.models.ScimGroupListEnterpriseMetaModel

import kotlinx.serialization.*

/**
 * 
 * @param schemas 
 * @param id 
 * @param externalId 
 * @param displayName 
 * @param members 
 * @param meta 
 */
@Serializable
data class ScimGroupListEnterpriseResourcesModel(
    @SerialName(value = "schemas")
    val schemas: kotlin.collections.List<kotlin.String>,
    @SerialName(value = "id")
    val id: kotlin.String,
    @SerialName(value = "externalId")
    val externalId: kotlin.String? = null,
    @SerialName(value = "displayName")
    val displayName: kotlin.String? = null,
    @SerialName(value = "members")
    val members: kotlin.collections.List<ScimGroupListEnterpriseMembersModel>? = null,
    @SerialName(value = "meta")
    val meta: ScimGroupListEnterpriseMetaModel? = null
) {

}

