/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models


import kotlinx.serialization.*

/**
 * 
 * @param `value` The email address.
 * @param type The type of email address.
 * @param primary Whether this email address is the primary address.
 */
@Serializable
data class ScimV2EnterprisesEnterpriseUsersEmailsModel(
    /* The email address. */
    @SerialName(value = "value")
    val `value`: kotlin.String,
    /* The type of email address. */
    @SerialName(value = "type")
    val type: kotlin.String,
    /* Whether this email address is the primary address. */
    @SerialName(value = "primary")
    val primary: kotlin.Boolean
) {

}

