/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.ShortBranchCommitModel

import kotlinx.serialization.*

/**
 * Tag
 * @param name 
 * @param commit 
 * @param zipballUrl 
 * @param tarballUrl 
 * @param nodeId 
 */
@Serializable
data class TagModel(
    @SerialName(value = "name")
    val name: kotlin.String,
    @SerialName(value = "commit")
    val commit: ShortBranchCommitModel,
    @SerialName(value = "zipball_url")
    val zipballUrl: kotlin.String,
    @SerialName(value = "tarball_url")
    val tarballUrl: kotlin.String,
    @SerialName(value = "node_id")
    val nodeId: kotlin.String
) {

}

