/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models

import jp.co.yumemi.android.code_check.data.models.SimpleMinusUserModel
import jp.co.yumemi.android.code_check.data.models.TimelineCrossReferencedEventSourceModel

import kotlinx.serialization.*

/**
 * Timeline Cross Referenced Event
 * @param event 
 * @param createdAt 
 * @param updatedAt 
 * @param source 
 * @param actor 
 */
@Serializable
data class TimelineMinusCrossMinusReferencedMinusEventModel(
    @SerialName(value = "event")
    val event: kotlin.String,
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,
    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String,
    @SerialName(value = "source")
    val source: TimelineCrossReferencedEventSourceModel,
    @SerialName(value = "actor")
    val actor: SimpleMinusUserModel? = null
) {

}

