/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.data.models


import kotlinx.serialization.*

/**
 * 
 * @param id 
 * @param name 
 * @param topicId 
 * @param relationType 
 */
@Serializable
data class TopicSearchResultItemTopicRelationModel(
    @SerialName(value = "id")
    val id: kotlin.Int? = null,
    @SerialName(value = "name")
    val name: kotlin.String? = null,
    @SerialName(value = "topic_id")
    val topicId: kotlin.Int? = null,
    @SerialName(value = "relation_type")
    val relationType: kotlin.String? = null
) {

}

