/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.AllowedMinusActionsApiModel

import kotlinx.serialization.*

/**
 * 
 * @param enabled Whether GitHub Actions is enabled on the repository.
 * @param allowedActions 
 * @param selectedActionsUrl The API URL to use to get or set the actions that are allowed to run, when `allowed_actions` is set to `selected`.
 */
@Serializable
data class ActionsMinusRepositoryMinusPermissionsApiModel(
    /* Whether GitHub Actions is enabled on the repository. */
    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,
    @Contextual @SerialName(value = "allowed_actions")
    val allowedActions: AllowedMinusActionsApiModel? = null,
    /* The API URL to use to get or set the actions that are allowed to run, when `allowed_actions` is set to `selected`. */
    @SerialName(value = "selected_actions_url")
    val selectedActionsUrl: kotlin.String? = null
) {

}

