/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models


import kotlinx.serialization.*

/**
 * An artifact
 * @param id 
 * @param nodeId 
 * @param name The name of the artifact.
 * @param sizeInBytes The size in bytes of the artifact.
 * @param url 
 * @param archiveDownloadUrl 
 * @param expired Whether or not the artifact has expired.
 * @param createdAt 
 * @param expiresAt 
 * @param updatedAt 
 */
@Serializable
data class ArtifactApiModel(
    @SerialName(value = "id")
    val id: kotlin.Int,
    @SerialName(value = "node_id")
    val nodeId: kotlin.String,
    /* The name of the artifact. */
    @SerialName(value = "name")
    val name: kotlin.String,
    /* The size in bytes of the artifact. */
    @SerialName(value = "size_in_bytes")
    val sizeInBytes: kotlin.Int,
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "archive_download_url")
    val archiveDownloadUrl: kotlin.String,
    /* Whether or not the artifact has expired. */
    @SerialName(value = "expired")
    val expired: kotlin.Boolean,
    @SerialName(value = "created_at")
    val createdAt: kotlin.String?,
    @SerialName(value = "expires_at")
    val expiresAt: kotlin.String?,
    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String?
) {

}

