/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.BranchRestrictionPolicyAppsApiModel
import io.github.gmvalentino8.github.sample.remote.models.BranchRestrictionPolicyTeamsApiModel
import io.github.gmvalentino8.github.sample.remote.models.RepositoryTemplateRepositoryOwnerApiModel

import kotlinx.serialization.*

/**
 * Branch Restriction Policy
 * @param url 
 * @param usersUrl 
 * @param teamsUrl 
 * @param appsUrl 
 * @param users 
 * @param teams 
 * @param apps 
 */
@Serializable
data class BranchMinusRestrictionMinusPolicyApiModel(
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "users_url")
    val usersUrl: kotlin.String,
    @SerialName(value = "teams_url")
    val teamsUrl: kotlin.String,
    @SerialName(value = "apps_url")
    val appsUrl: kotlin.String,
    @SerialName(value = "users")
    val users: kotlin.collections.List<RepositoryTemplateRepositoryOwnerApiModel>,
    @SerialName(value = "teams")
    val teams: kotlin.collections.List<BranchRestrictionPolicyTeamsApiModel>,
    @SerialName(value = "apps")
    val apps: kotlin.collections.List<BranchRestrictionPolicyAppsApiModel>
) {

}

