/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models


import kotlinx.serialization.*

/**
 * Details about the codespace's git repository.
 * @param ahead The number of commits the local repository is ahead of the remote.
 * @param behind The number of commits the local repository is behind the remote.
 * @param hasUnpushedChanges Whether the local repository has unpushed changes.
 * @param hasUncommittedChanges Whether the local repository has uncommitted changes.
 * @param ref The current branch (or SHA if in detached HEAD state) of the local repository.
 */
@Serializable
data class CodespaceGitStatusApiModel(
    /* The number of commits the local repository is ahead of the remote. */
    @SerialName(value = "ahead")
    val ahead: kotlin.Int? = null,
    /* The number of commits the local repository is behind the remote. */
    @SerialName(value = "behind")
    val behind: kotlin.Int? = null,
    /* Whether the local repository has unpushed changes. */
    @SerialName(value = "has_unpushed_changes")
    val hasUnpushedChanges: kotlin.Boolean? = null,
    /* Whether the local repository has uncommitted changes. */
    @SerialName(value = "has_uncommitted_changes")
    val hasUncommittedChanges: kotlin.Boolean? = null,
    /* The current branch (or SHA if in detached HEAD state) of the local repository. */
    @SerialName(value = "ref")
    val ref: kotlin.String? = null
) {

}

