/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.CommitCommitApiModel
import io.github.gmvalentino8.github.sample.remote.models.CommitParentsApiModel
import io.github.gmvalentino8.github.sample.remote.models.CommitStatsApiModel
import io.github.gmvalentino8.github.sample.remote.models.DiffMinusEntryApiModel
import io.github.gmvalentino8.github.sample.remote.models.NullableMinusSimpleMinusUserApiModel

import kotlinx.serialization.*

/**
 * Commit
 * @param url 
 * @param sha 
 * @param nodeId 
 * @param htmlUrl 
 * @param commentsUrl 
 * @param commit 
 * @param author 
 * @param committer 
 * @param parents 
 * @param stats 
 * @param files 
 */
@Serializable
data class CommitApiModel(
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "sha")
    val sha: kotlin.String,
    @SerialName(value = "node_id")
    val nodeId: kotlin.String,
    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String,
    @SerialName(value = "comments_url")
    val commentsUrl: kotlin.String,
    @SerialName(value = "commit")
    val commit: CommitCommitApiModel,
    @SerialName(value = "author")
    val author: NullableMinusSimpleMinusUserApiModel?,
    @SerialName(value = "committer")
    val committer: NullableMinusSimpleMinusUserApiModel?,
    @SerialName(value = "parents")
    val parents: kotlin.collections.List<CommitParentsApiModel>,
    @SerialName(value = "stats")
    val stats: CommitStatsApiModel? = null,
    @SerialName(value = "files")
    val files: kotlin.collections.List<DiffMinusEntryApiModel>? = null
) {

}

