/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.ScimV2EnterprisesEnterpriseGroupsMembersApiModel

import kotlinx.serialization.*

/**
 * 
 * @param schemas The SCIM schema URIs.
 * @param displayName The name of the SCIM group. This must match the GitHub organization that the group maps to.
 * @param members 
 */
@Serializable
data class InlineObject143ApiModel(
    /* The SCIM schema URIs. */
    @SerialName(value = "schemas")
    val schemas: kotlin.collections.List<kotlin.String>,
    /* The name of the SCIM group. This must match the GitHub organization that the group maps to. */
    @SerialName(value = "displayName")
    val displayName: kotlin.String,
    @SerialName(value = "members")
    val members: kotlin.collections.List<ScimV2EnterprisesEnterpriseGroupsMembersApiModel>? = null
) {

}

