/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.TeamsTeamIdTeamSyncGroupMappingsGroupsApiModel

import kotlinx.serialization.*

/**
 * 
 * @param groups The IdP groups you want to connect to a GitHub team. When updating, the new `groups` object will replace the original one. You must include any existing groups that you don't want to remove.
 * @param syncedAt 
 */
@Serializable
data class InlineObject161ApiModel(
    /* The IdP groups you want to connect to a GitHub team. When updating, the new `groups` object will replace the original one. You must include any existing groups that you don't want to remove. */
    @SerialName(value = "groups")
    val groups: kotlin.collections.List<TeamsTeamIdTeamSyncGroupMappingsGroupsApiModel>,
    @SerialName(value = "synced_at")
    val syncedAt: kotlin.String? = null
) {

}

