/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 * @param repositories A list of arrays indicating which repositories should be migrated.
 * @param lockRepositories Indicates whether repositories should be locked (to prevent manipulation) while migrating data.
 * @param excludeAttachments Indicates whether attachments should be excluded from the migration (to reduce migration archive file size).
 * @param excludeReleases Indicates whether releases should be excluded from the migration (to reduce migration archive file size).
 * @param excludeOwnerProjects Indicates whether projects owned by the organization or users should be excluded. from the migration.
 * @param exclude 
 */
@Serializable
data class InlineObject34ApiModel(
    /* A list of arrays indicating which repositories should be migrated. */
    @SerialName(value = "repositories")
    val repositories: kotlin.collections.List<kotlin.String>,
    /* Indicates whether repositories should be locked (to prevent manipulation) while migrating data. */
    @SerialName(value = "lock_repositories")
    val lockRepositories: kotlin.Boolean? = false,
    /* Indicates whether attachments should be excluded from the migration (to reduce migration archive file size). */
    @SerialName(value = "exclude_attachments")
    val excludeAttachments: kotlin.Boolean? = false,
    /* Indicates whether releases should be excluded from the migration (to reduce migration archive file size). */
    @SerialName(value = "exclude_releases")
    val excludeReleases: kotlin.Boolean? = false,
    /* Indicates whether projects owned by the organization or users should be excluded. from the migration. */
    @SerialName(value = "exclude_owner_projects")
    val excludeOwnerProjects: kotlin.Boolean? = false,
    @SerialName(value = "exclude")
    val exclude: kotlin.collections.List<InlineObject34ApiModel.Exclude>? = null
) {

    /**
     * 
     * Values: repositories
     */
    @Serializable(with = Exclude.Serializer::class)
    enum class Exclude(val value: kotlin.String) {
        repositories("repositories");

        @kotlinx.serialization.Serializer(forClass = Exclude::class)
        object Serializer {
            override fun deserialize(decoder: Decoder): Exclude {
                val decoded = decoder.decodeString()
                return values().first { it.value == decoded }
            }

            override val descriptor: SerialDescriptor
                get() = PrimitiveSerialDescriptor(
                    "InlineObject34ApiModel.Exclude.Serializer",
                    PrimitiveKind.STRING
                )

            override fun serialize(encoder: Encoder, value: Exclude) {
                return encoder.encodeString(value.value)
            }
        }
    }
}

