/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The duration of the interaction restriction. Can be one of: `one_day`, `three_days`, `one_week`, `one_month`, `six_months`. Default: `one_day`.
 *
 * Values: oneDay,threeDays,oneWeek,oneMonth,sixMonths
 */
@Serializable
enum class InteractionMinusExpiryApiModel(val value: kotlin.String) {

    @SerialName(value = "one_day")
    oneDay("one_day"),

    @SerialName(value = "three_days")
    threeDays("three_days"),

    @SerialName(value = "one_week")
    oneWeek("one_week"),

    @SerialName(value = "one_month")
    oneMonth("one_month"),

    @SerialName(value = "six_months")
    sixMonths("six_months");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): kotlin.String? = if (data is InteractionMinusExpiryApiModel) "$data" else null

        /**
         * Returns a valid [InteractionMinusExpiryApiModel] for [data], null otherwise.
         */
        fun decode(data: Any?): InteractionMinusExpiryApiModel? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

