/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.InteractionMinusExpiryApiModel
import io.github.gmvalentino8.github.sample.remote.models.InteractionMinusGroupApiModel

import kotlinx.serialization.*

/**
 * Limit interactions to a specific type of user for a specified duration
 * @param limit 
 * @param expiry 
 */
@Serializable
data class InteractionMinusLimitApiModel(
    @Contextual @SerialName(value = "limit")
    val limit: InteractionMinusGroupApiModel,
    @Contextual @SerialName(value = "expiry")
    val expiry: InteractionMinusExpiryApiModel? = null
) {

}

