/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.NullableMinusSimpleMinusUserApiModel

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Projects are a way to organize columns and cards of work.
 * @param ownerUrl 
 * @param url 
 * @param htmlUrl 
 * @param columnsUrl 
 * @param id 
 * @param nodeId 
 * @param name Name of the project
 * @param body Body of the project
 * @param number 
 * @param state State of the project; either 'open' or 'closed'
 * @param creator 
 * @param createdAt 
 * @param updatedAt 
 * @param organizationPermission The baseline permission that all organization members have on this project. Only present if owner is an organization.
 * @param `private` Whether or not this project can be seen by everyone. Only present if owner is an organization.
 */
@Serializable
data class ProjectApiModel(
    @SerialName(value = "owner_url")
    val ownerUrl: kotlin.String,
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String,
    @SerialName(value = "columns_url")
    val columnsUrl: kotlin.String,
    @SerialName(value = "id")
    val id: kotlin.Int,
    @SerialName(value = "node_id")
    val nodeId: kotlin.String,
    /* Name of the project */
    @SerialName(value = "name")
    val name: kotlin.String,
    /* Body of the project */
    @SerialName(value = "body")
    val body: kotlin.String?,
    @SerialName(value = "number")
    val number: kotlin.Int,
    /* State of the project; either 'open' or 'closed' */
    @SerialName(value = "state")
    val state: kotlin.String,
    @SerialName(value = "creator")
    val creator: NullableMinusSimpleMinusUserApiModel?,
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,
    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String,
    /* The baseline permission that all organization members have on this project. Only present if owner is an organization. */
    @SerialName(value = "organization_permission")
    val organizationPermission: ProjectApiModel.OrganizationPermission? = null,
    /* Whether or not this project can be seen by everyone. Only present if owner is an organization. */
    @SerialName(value = "private")
    val `private`: kotlin.Boolean? = null
) {

    /**
     * The baseline permission that all organization members have on this project. Only present if owner is an organization.
     * Values: read,write,admin,none
     */
    @Serializable(with = OrganizationPermission.Serializer::class)
    enum class OrganizationPermission(val value: kotlin.String) {
        read("read"),
        write("write"),
        admin("admin"),
        none("none");

        @kotlinx.serialization.Serializer(forClass = OrganizationPermission::class)
        object Serializer {
            override fun deserialize(decoder: Decoder): OrganizationPermission {
                val decoded = decoder.decodeString()
                return values().first { it.value == decoded }
            }

            override val descriptor: SerialDescriptor
                get() = PrimitiveSerialDescriptor(
                    "ProjectApiModel.OrganizationPermission.Serializer",
                    PrimitiveKind.STRING
                )

            override fun serialize(encoder: Encoder, value: OrganizationPermission) {
                return encoder.encodeString(value.value)
            }
        }
    }
}

