/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.SimpleMinusUserApiModel
import io.github.gmvalentino8.github.sample.remote.models.TeamApiModel

import kotlinx.serialization.*

/**
 * 
 * @param users 
 * @param teams 
 */
@Serializable
data class ProtectedBranchRequiredPullRequestReviewsBypassPullRequestAllowancesApiModel(
    @SerialName(value = "users")
    val users: kotlin.collections.List<SimpleMinusUserApiModel>,
    @SerialName(value = "teams")
    val teams: kotlin.collections.List<TeamApiModel>
) {

}

