/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.SimpleMinusUserApiModel
import io.github.gmvalentino8.github.sample.remote.models.TeamApiModel

import kotlinx.serialization.*

/**
 * Allow specific users or teams to bypass pull request requirements. Set to `null` to disable.
 * @param users The list of users allowed to bypass pull request requirements.
 * @param teams The list of teams allowed to bypass pull request requirements.
 */
@Serializable
data class ProtectedBranchPullRequestReviewBypassPullRequestAllowancesApiModel(
    /* The list of users allowed to bypass pull request requirements. */
    @SerialName(value = "users")
    val users: kotlin.collections.List<SimpleMinusUserApiModel>? = null,
    /* The list of teams allowed to bypass pull request requirements. */
    @SerialName(value = "teams")
    val teams: kotlin.collections.List<TeamApiModel>? = null
) {

}

