/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.NullableMinusSimpleMinusUserApiModel
import io.github.gmvalentino8.github.sample.remote.models.RepositoryApiModel

import kotlinx.serialization.*

/**
 * 
 * @param label 
 * @param ref 
 * @param repo 
 * @param sha 
 * @param user 
 */
@Serializable
data class PullRequestSimpleHeadApiModel(
    @SerialName(value = "label")
    val label: kotlin.String,
    @SerialName(value = "ref")
    val ref: kotlin.String,
    @SerialName(value = "repo")
    val repo: RepositoryApiModel,
    @SerialName(value = "sha")
    val sha: kotlin.String,
    @SerialName(value = "user")
    val user: NullableMinusSimpleMinusUserApiModel?
) {

}

