/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.ReposRepoNameSecurityAndAnalysisAdvancedSecurityApiModel
import io.github.gmvalentino8.github.sample.remote.models.ReposRepoNameSecurityAndAnalysisSecretScanningApiModel

import kotlinx.serialization.*

/**
 * Specify which security and analysis features to enable or disable. For example, to enable GitHub Advanced Security, use this data in the body of the PATCH request: `{\"security_and_analysis\": {\"advanced_security\": {\"status\": \"enabled\"}}}`. If you have admin permissions for a private repository covered by an Advanced Security license, you can check which security and analysis features are currently enabled by using a `GET /repos/{repo_name}` request.
 * @param advancedSecurity 
 * @param secretScanning 
 */
@Serializable
data class ReposRepoNameSecurityAndAnalysisApiModel(
    @SerialName(value = "advanced_security")
    val advancedSecurity: ReposRepoNameSecurityAndAnalysisAdvancedSecurityApiModel? = null,
    @SerialName(value = "secret_scanning")
    val secretScanning: ReposRepoNameSecurityAndAnalysisSecretScanningApiModel? = null
) {

}

