/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models


import kotlinx.serialization.*

/**
 * 
 * @param resourceType 
 * @param created 
 * @param lastModified 
 * @param location 
 */
@Serializable
data class ScimUserMetaApiModel(
    @SerialName(value = "resourceType")
    val resourceType: kotlin.String? = null,
    @SerialName(value = "created")
    val created: kotlin.String? = null,
    @SerialName(value = "lastModified")
    val lastModified: kotlin.String? = null,
    @SerialName(value = "location")
    val location: kotlin.String? = null
) {

}

