/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models


import kotlinx.serialization.*

/**
 * 
 * @param givenName The first name of the user.
 * @param familyName The last name of the user.
 */
@Serializable
data class ScimV2EnterprisesEnterpriseUsersNameApiModel(
    /* The first name of the user. */
    @SerialName(value = "givenName")
    val givenName: kotlin.String,
    /* The last name of the user. */
    @SerialName(value = "familyName")
    val familyName: kotlin.String
) {

}

