/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.ScimUserListEnterpriseResourcesApiModel

import kotlinx.serialization.*

/**
 * 
 * @param schemas 
 * @param totalResults 
 * @param itemsPerPage 
 * @param startIndex 
 * @param resources 
 */
@Serializable
data class ScimMinusUserMinusListMinusEnterpriseApiModel(
    @SerialName(value = "schemas")
    val schemas: kotlin.collections.List<kotlin.String>,
    @Contextual @SerialName(value = "totalResults")
    val totalResults: kotlin.Double,
    @Contextual @SerialName(value = "itemsPerPage")
    val itemsPerPage: kotlin.Double,
    @Contextual @SerialName(value = "startIndex")
    val startIndex: kotlin.Double,
    @SerialName(value = "Resources")
    val resources: kotlin.collections.List<ScimUserListEnterpriseResourcesApiModel>
) {

}

