/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models


import kotlinx.serialization.*

/**
 * Simple User
 * @param login 
 * @param id 
 * @param nodeId 
 * @param avatarUrl 
 * @param gravatarId 
 * @param url 
 * @param htmlUrl 
 * @param followersUrl 
 * @param followingUrl 
 * @param gistsUrl 
 * @param starredUrl 
 * @param subscriptionsUrl 
 * @param organizationsUrl 
 * @param reposUrl 
 * @param eventsUrl 
 * @param receivedEventsUrl 
 * @param type 
 * @param siteAdmin 
 * @param name 
 * @param email 
 * @param starredAt 
 */
@Serializable
data class SimpleMinusUserApiModel(
    @SerialName(value = "login")
    val login: kotlin.String,
    @SerialName(value = "id")
    val id: kotlin.Int,
    @SerialName(value = "node_id")
    val nodeId: kotlin.String,
    @SerialName(value = "avatar_url")
    val avatarUrl: kotlin.String,
    @SerialName(value = "gravatar_id")
    val gravatarId: kotlin.String?,
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String,
    @SerialName(value = "followers_url")
    val followersUrl: kotlin.String,
    @SerialName(value = "following_url")
    val followingUrl: kotlin.String,
    @SerialName(value = "gists_url")
    val gistsUrl: kotlin.String,
    @SerialName(value = "starred_url")
    val starredUrl: kotlin.String,
    @SerialName(value = "subscriptions_url")
    val subscriptionsUrl: kotlin.String,
    @SerialName(value = "organizations_url")
    val organizationsUrl: kotlin.String,
    @SerialName(value = "repos_url")
    val reposUrl: kotlin.String,
    @SerialName(value = "events_url")
    val eventsUrl: kotlin.String,
    @SerialName(value = "received_events_url")
    val receivedEventsUrl: kotlin.String,
    @SerialName(value = "type")
    val type: kotlin.String,
    @SerialName(value = "site_admin")
    val siteAdmin: kotlin.Boolean,
    @SerialName(value = "name")
    val name: kotlin.String? = null,
    @SerialName(value = "email")
    val email: kotlin.String? = null,
    @SerialName(value = "starred_at")
    val starredAt: kotlin.String? = null
) {

}

