/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.gmvalentino8.github.sample.remote.models

import io.github.gmvalentino8.github.sample.remote.models.IssueApiModel

import kotlinx.serialization.*

/**
 * 
 * @param type 
 * @param issue 
 */
@Serializable
data class TimelineCrossReferencedEventSourceApiModel(
    @SerialName(value = "type")
    val type: kotlin.String? = null,
    @SerialName(value = "issue")
    val issue: IssueApiModel? = null
) {

}

