@startuml Search
state Search {
    state Initial {
        Initial : I.OnStart > A.LoadRecentSearches > R.RecentSearches
        
        Initial -right-> Stable.EmptySearch : R.RecentSearches
    }

    state Stable {
        Stable : I.InputSearchText > A.UpdateSearchText > R.UpdateSearchText
        Stable : I.ClickBack > A.NavigateBack > E.NavigateBack

        state Stable.EmptySearch {
            Stable.EmptySearch : I.ClickClearRecentSearches > A.ClearRecentSearches > R.ClearRecentSearches
            Stable.EmptySearch : I.ClickRecentSearchItem > A.UpdateSearchText > R.UpdateSearchText

            Stable.EmptySearch --> Stable.NonEmptySearch : R.UpdateSearchText
            Stable.EmptySearch --> Stable.EmptySearch : R.ClearRecentSearches
        }

        state Stable.NonEmptySearch {
            Stable.NonEmptySearch : I.ClickItem(type) > A.NavigateSearch(type) > E.NavigateSearch(type)
            Stable.NonEmptySearch : I.ClickClearSearchText > A.UpdateSearchText > R.UpdateSearchText

            Stable.NonEmptySearch --> Stable.EmptySearch : R.UpdateSearchText
        }
    }
}
@enduml
