/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models

import jp.co.yumemi.android.code_check.remote.models.AllowedMinusActionsApiModel
import jp.co.yumemi.android.code_check.remote.models.EnabledMinusRepositoriesApiModel

import kotlinx.serialization.*

/**
 * 
 * @param enabledRepositories 
 * @param selectedRepositoriesUrl The API URL to use to get or set the selected repositories that are allowed to run GitHub Actions, when `enabled_repositories` is set to `selected`.
 * @param allowedActions 
 * @param selectedActionsUrl The API URL to use to get or set the actions that are allowed to run, when `allowed_actions` is set to `selected`.
 */
@Serializable
data class ActionsMinusOrganizationMinusPermissionsApiModel(
    @Contextual @SerialName(value = "enabled_repositories")
    val enabledRepositories: EnabledMinusRepositoriesApiModel,
    /* The API URL to use to get or set the selected repositories that are allowed to run GitHub Actions, when `enabled_repositories` is set to `selected`. */
    @SerialName(value = "selected_repositories_url")
    val selectedRepositoriesUrl: kotlin.String? = null,
    @Contextual @SerialName(value = "allowed_actions")
    val allowedActions: AllowedMinusActionsApiModel? = null,
    /* The API URL to use to get or set the actions that are allowed to run, when `allowed_actions` is set to `selected`. */
    @SerialName(value = "selected_actions_url")
    val selectedActionsUrl: kotlin.String? = null
) {

}

