/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models

import jp.co.yumemi.android.code_check.remote.models.CheckRunCheckSuiteApiModel
import jp.co.yumemi.android.code_check.remote.models.CheckRunOutputApiModel
import jp.co.yumemi.android.code_check.remote.models.DeploymentMinusSimpleApiModel
import jp.co.yumemi.android.code_check.remote.models.NullableMinusIntegrationApiModel
import jp.co.yumemi.android.code_check.remote.models.PullMinusRequestMinusMinimalApiModel

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * A check performed on the code of a given code change
 * @param id The id of the check.
 * @param headSha The SHA of the commit that is being checked.
 * @param nodeId 
 * @param externalId 
 * @param url 
 * @param htmlUrl 
 * @param detailsUrl 
 * @param status The phase of the lifecycle that the check is currently in.
 * @param conclusion 
 * @param startedAt 
 * @param completedAt 
 * @param output 
 * @param name The name of the check.
 * @param checkSuite 
 * @param app 
 * @param pullRequests 
 * @param deployment 
 */
@Serializable
data class CheckMinusRunApiModel(
    /* The id of the check. */
    @SerialName(value = "id")
    val id: kotlin.Int,
    /* The SHA of the commit that is being checked. */
    @SerialName(value = "head_sha")
    val headSha: kotlin.String,
    @SerialName(value = "node_id")
    val nodeId: kotlin.String,
    @SerialName(value = "external_id")
    val externalId: kotlin.String?,
    @SerialName(value = "url")
    val url: kotlin.String,
    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String?,
    @SerialName(value = "details_url")
    val detailsUrl: kotlin.String?,
    /* The phase of the lifecycle that the check is currently in. */
    @SerialName(value = "status")
    val status: CheckMinusRunApiModel.Status,
    @SerialName(value = "conclusion")
    val conclusion: CheckMinusRunApiModel.Conclusion?,
    @SerialName(value = "started_at")
    val startedAt: kotlin.String?,
    @SerialName(value = "completed_at")
    val completedAt: kotlin.String?,
    @SerialName(value = "output")
    val output: CheckRunOutputApiModel,
    /* The name of the check. */
    @SerialName(value = "name")
    val name: kotlin.String,
    @SerialName(value = "check_suite")
    val checkSuite: CheckRunCheckSuiteApiModel?,
    @SerialName(value = "app")
    val app: NullableMinusIntegrationApiModel?,
    @SerialName(value = "pull_requests")
    val pullRequests: kotlin.collections.List<PullMinusRequestMinusMinimalApiModel>,
    @SerialName(value = "deployment")
    val deployment: DeploymentMinusSimpleApiModel? = null
) {

    /**
     * The phase of the lifecycle that the check is currently in.
     * Values: queued,inProgress,completed
     */
    @Serializable(with = Status.Serializer::class)
    enum class Status(val value: kotlin.String) {
        queued("queued"),
        inProgress("in_progress"),
        completed("completed");

        @kotlinx.serialization.Serializer(forClass = Status::class)
        object Serializer {
            override fun deserialize(decoder: Decoder): Status {
                val decoded = decoder.decodeString()
                return values().first { it.value == decoded }
            }

            override val descriptor: SerialDescriptor
                get() = PrimitiveSerialDescriptor(
                    "CheckMinusRunApiModel.Status.Serializer",
                    PrimitiveKind.STRING
                )

            override fun serialize(encoder: Encoder, value: Status) {
                return encoder.encodeString(value.value)
            }
        }
    }
    /**
     * 
     * Values: success,failure,neutral,cancelled,skipped,timedOut,actionRequired
     */
    @Serializable(with = Conclusion.Serializer::class)
    enum class Conclusion(val value: kotlin.String) {
        success("success"),
        failure("failure"),
        neutral("neutral"),
        cancelled("cancelled"),
        skipped("skipped"),
        timedOut("timed_out"),
        actionRequired("action_required");

        @kotlinx.serialization.Serializer(forClass = Conclusion::class)
        object Serializer {
            override fun deserialize(decoder: Decoder): Conclusion {
                val decoded = decoder.decodeString()
                return values().first { it.value == decoded }
            }

            override val descriptor: SerialDescriptor
                get() = PrimitiveSerialDescriptor(
                    "CheckMinusRunApiModel.Conclusion.Serializer",
                    PrimitiveKind.STRING
                )

            override fun serialize(encoder: Encoder, value: Conclusion) {
                return encoder.encodeString(value.value)
            }
        }
    }
}

