/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*

/**
 * Successful deletion of a code scanning analysis
 * @param nextAnalysisUrl Next deletable analysis in chain, without last analysis deletion confirmation
 * @param confirmDeleteUrl Next deletable analysis in chain, with last analysis deletion confirmation
 */
@Serializable
data class CodeMinusScanningMinusAnalysisMinusDeletionApiModel(
    /* Next deletable analysis in chain, without last analysis deletion confirmation */
    @SerialName(value = "next_analysis_url")
    val nextAnalysisUrl: kotlin.String?,
    /* Next deletable analysis in chain, with last analysis deletion confirmation */
    @SerialName(value = "confirm_delete_url")
    val confirmDeleteUrl: kotlin.String?
) {

}

