/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 * @param id A unique identifier for the rule used to detect the alert.
 * @param name The name of the rule used to detect the alert.
 * @param tags A set of tags applicable for the rule.
 * @param severity The severity of the alert.
 * @param description A short description of the rule used to detect the alert.
 */
@Serializable
data class CodeMinusScanningMinusAlertMinusRuleMinusSummaryApiModel(
    /* A unique identifier for the rule used to detect the alert. */
    @SerialName(value = "id")
    val id: kotlin.String? = null,
    /* The name of the rule used to detect the alert. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,
    /* A set of tags applicable for the rule. */
    @SerialName(value = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,
    /* The severity of the alert. */
    @SerialName(value = "severity")
    val severity: CodeMinusScanningMinusAlertMinusRuleMinusSummaryApiModel.Severity? = null,
    /* A short description of the rule used to detect the alert. */
    @SerialName(value = "description")
    val description: kotlin.String? = null
) {

    /**
     * The severity of the alert.
     * Values: none,note,warning,error
     */
    @Serializable(with = Severity.Serializer::class)
    enum class Severity(val value: kotlin.String) {
        none("none"),
        note("note"),
        warning("warning"),
        error("error");

        @kotlinx.serialization.Serializer(forClass = Severity::class)
        object Serializer {
            override fun deserialize(decoder: Decoder): Severity {
                val decoded = decoder.decodeString()
                return values().first { it.value == decoded }
            }

            override val descriptor: SerialDescriptor
                get() = PrimitiveSerialDescriptor(
                    "CodeMinusScanningMinusAlertMinusRuleMinusSummaryApiModel.Severity.Serializer",
                    PrimitiveKind.STRING
                )

            override fun serialize(encoder: Encoder, value: Severity) {
                return encoder.encodeString(value.value)
            }
        }
    }
}

