/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models

import jp.co.yumemi.android.code_check.remote.models.NullableMinusCodeMinusOfMinusConductMinusSimpleApiModel
import jp.co.yumemi.android.code_check.remote.models.NullableMinusCommunityMinusHealthMinusFileApiModel
import jp.co.yumemi.android.code_check.remote.models.NullableMinusLicenseMinusSimpleApiModel

import kotlinx.serialization.*

/**
 * 
 * @param codeOfConduct 
 * @param codeOfConductFile 
 * @param license 
 * @param contributing 
 * @param readme 
 * @param issueTemplate 
 * @param pullRequestTemplate 
 */
@Serializable
data class CommunityProfileFilesApiModel(
    @SerialName(value = "code_of_conduct")
    val codeOfConduct: NullableMinusCodeMinusOfMinusConductMinusSimpleApiModel?,
    @SerialName(value = "code_of_conduct_file")
    val codeOfConductFile: NullableMinusCommunityMinusHealthMinusFileApiModel?,
    @SerialName(value = "license")
    val license: NullableMinusLicenseMinusSimpleApiModel?,
    @SerialName(value = "contributing")
    val contributing: NullableMinusCommunityMinusHealthMinusFileApiModel?,
    @SerialName(value = "readme")
    val readme: NullableMinusCommunityMinusHealthMinusFileApiModel?,
    @SerialName(value = "issue_template")
    val issueTemplate: NullableMinusCommunityMinusHealthMinusFileApiModel?,
    @SerialName(value = "pull_request_template")
    val pullRequestTemplate: NullableMinusCommunityMinusHealthMinusFileApiModel?
) {

}

