/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*

/**
 * 
 * @param pageName 
 * @param title 
 * @param summary 
 * @param action 
 * @param sha 
 * @param htmlUrl 
 */
@Serializable
data class EventPayloadPagesApiModel(
    @SerialName(value = "page_name")
    val pageName: kotlin.String? = null,
    @SerialName(value = "title")
    val title: kotlin.String? = null,
    @SerialName(value = "summary")
    val summary: kotlin.String? = null,
    @SerialName(value = "action")
    val action: kotlin.String? = null,
    @SerialName(value = "sha")
    val sha: kotlin.String? = null,
    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String? = null
) {

}

