/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*

/**
 * 
 * @param date 
 * @param email 
 * @param name 
 */
@Serializable
data class GitTagTaggerApiModel(
    @SerialName(value = "date")
    val date: kotlin.String,
    @SerialName(value = "email")
    val email: kotlin.String,
    @SerialName(value = "name")
    val name: kotlin.String
) {

}

