/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*

/**
 * 
 * @param id 
 * @param primaryKeyId 
 * @param keyId 
 * @param publicKey 
 * @param emails 
 * @param subkeys 
 * @param canSign 
 * @param canEncryptComms 
 * @param canEncryptStorage 
 * @param canCertify 
 * @param createdAt 
 * @param expiresAt 
 * @param rawKey 
 */
@Serializable
data class GpgKeySubkeysApiModel(
    @SerialName(value = "id")
    val id: kotlin.Int? = null,
    @SerialName(value = "primary_key_id")
    val primaryKeyId: kotlin.Int? = null,
    @SerialName(value = "key_id")
    val keyId: kotlin.String? = null,
    @SerialName(value = "public_key")
    val publicKey: kotlin.String? = null,
    @SerialName(value = "emails")
    val emails: kotlin.collections.List<@Contextual kotlin.Any>? = null,
    @SerialName(value = "subkeys")
    val subkeys: kotlin.collections.List<@Contextual kotlin.Any>? = null,
    @SerialName(value = "can_sign")
    val canSign: kotlin.Boolean? = null,
    @SerialName(value = "can_encrypt_comms")
    val canEncryptComms: kotlin.Boolean? = null,
    @SerialName(value = "can_encrypt_storage")
    val canEncryptStorage: kotlin.Boolean? = null,
    @SerialName(value = "can_certify")
    val canCertify: kotlin.Boolean? = null,
    @SerialName(value = "created_at")
    val createdAt: kotlin.String? = null,
    @SerialName(value = "expires_at")
    val expiresAt: kotlin.String? = null,
    @SerialName(value = "raw_key")
    val rawKey: kotlin.String? = null
) {

}

