/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*

/**
 * 
 * @param groupId The ID of the group
 * @param groupName The name of the group
 * @param groupDescription a description of the group
 * @param status synchronization status for this group mapping
 * @param syncedAt the time of the last sync for this group-mapping
 */
@Serializable
data class GroupMappingGroupsApiModel(
    /* The ID of the group */
    @SerialName(value = "group_id")
    val groupId: kotlin.String,
    /* The name of the group */
    @SerialName(value = "group_name")
    val groupName: kotlin.String,
    /* a description of the group */
    @SerialName(value = "group_description")
    val groupDescription: kotlin.String,
    /* synchronization status for this group mapping */
    @SerialName(value = "status")
    val status: kotlin.String? = null,
    /* the time of the last sync for this group-mapping */
    @SerialName(value = "synced_at")
    val syncedAt: kotlin.String? = null
) {

}

