/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models

import jp.co.yumemi.android.code_check.remote.models.HovercardContextsApiModel

import kotlinx.serialization.*

/**
 * Hovercard
 * @param contexts 
 */
@Serializable
data class HovercardApiModel(
    @SerialName(value = "contexts")
    val contexts: kotlin.collections.List<HovercardContextsApiModel>
) {

}

