/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 * @param inviteeId **Required unless you provide `email`**. GitHub user ID for the person you are inviting.
 * @param email **Required unless you provide `invitee_id`**. Email address of the person you are inviting, which can be an existing GitHub user.
 * @param role Specify role for new member. Can be one of:   \\* `admin` - Organization owners with full administrative rights to the organization and complete access to all repositories and teams.   \\* `direct_member` - Non-owner organization members with ability to see other members and join teams by invitation.   \\* `billing_manager` - Non-owner organization members with ability to manage the billing settings of your organization.
 * @param teamIds Specify IDs for the teams you want to invite new members to.
 */
@Serializable
data class InlineObject32ApiModel(
    /* **Required unless you provide `email`**. GitHub user ID for the person you are inviting. */
    @SerialName(value = "invitee_id")
    val inviteeId: kotlin.Int? = null,
    /* **Required unless you provide `invitee_id`**. Email address of the person you are inviting, which can be an existing GitHub user. */
    @SerialName(value = "email")
    val email: kotlin.String? = null,
    /* Specify role for new member. Can be one of:   \\* `admin` - Organization owners with full administrative rights to the organization and complete access to all repositories and teams.   \\* `direct_member` - Non-owner organization members with ability to see other members and join teams by invitation.   \\* `billing_manager` - Non-owner organization members with ability to manage the billing settings of your organization. */
    @SerialName(value = "role")
    val role: InlineObject32ApiModel.Role? = Role.directMember,
    /* Specify IDs for the teams you want to invite new members to. */
    @SerialName(value = "team_ids")
    val teamIds: kotlin.collections.List<kotlin.Int>? = null
) {

    /**
     * Specify role for new member. Can be one of:   \\* `admin` - Organization owners with full administrative rights to the organization and complete access to all repositories and teams.   \\* `direct_member` - Non-owner organization members with ability to see other members and join teams by invitation.   \\* `billing_manager` - Non-owner organization members with ability to manage the billing settings of your organization.
     * Values: admin,directMember,billingManager
     */
    @Serializable(with = Role.Serializer::class)
    enum class Role(val value: kotlin.String) {
        admin("admin"),
        directMember("direct_member"),
        billingManager("billing_manager");

        @kotlinx.serialization.Serializer(forClass = Role::class)
        object Serializer {
            override fun deserialize(decoder: Decoder): Role {
                val decoded = decoder.decodeString()
                return values().first { it.value == decoded }
            }

            override val descriptor: SerialDescriptor
                get() = PrimitiveSerialDescriptor(
                    "InlineObject32ApiModel.Role.Serializer",
                    PrimitiveKind.STRING
                )

            override fun serialize(encoder: Encoder, value: Role) {
                return encoder.encodeString(value.value)
            }
        }
    }
}

