/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*

/**
 * 
 * @param position The position of the card in a column. Can be one of: `top`, `bottom`, or `after:<card_id>` to place after the specified card.
 * @param columnId The unique identifier of the column the card should be moved to
 */
@Serializable
data class InlineObject51ApiModel(
    /* The position of the card in a column. Can be one of: `top`, `bottom`, or `after:<card_id>` to place after the specified card. */
    @SerialName(value = "position")
    val position: kotlin.String,
    /* The unique identifier of the column the card should be moved to */
    @SerialName(value = "column_id")
    val columnId: kotlin.Int? = null
) {

}

