/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models

import jp.co.yumemi.android.code_check.remote.models.ScimV2EnterprisesEnterpriseUsersEmailsApiModel
import jp.co.yumemi.android.code_check.remote.models.ScimV2EnterprisesEnterpriseUsersGroupsApiModel
import jp.co.yumemi.android.code_check.remote.models.ScimV2EnterprisesEnterpriseUsersNameApiModel

import kotlinx.serialization.*

/**
 * 
 * @param schemas The SCIM schema URIs.
 * @param userName The username for the user.
 * @param name 
 * @param emails List of user emails.
 * @param groups List of SCIM group IDs the user is a member of.
 */
@Serializable
data class InlineObject145ApiModel(
    /* The SCIM schema URIs. */
    @SerialName(value = "schemas")
    val schemas: kotlin.collections.List<kotlin.String>,
    /* The username for the user. */
    @SerialName(value = "userName")
    val userName: kotlin.String,
    @SerialName(value = "name")
    val name: ScimV2EnterprisesEnterpriseUsersNameApiModel,
    /* List of user emails. */
    @SerialName(value = "emails")
    val emails: kotlin.collections.List<ScimV2EnterprisesEnterpriseUsersEmailsApiModel>,
    /* List of SCIM group IDs the user is a member of. */
    @SerialName(value = "groups")
    val groups: kotlin.collections.List<ScimV2EnterprisesEnterpriseUsersGroupsApiModel>? = null
) {

}

