/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*

/**
 * 
 * @param code 
 * @param message 
 * @param resource 
 * @param `field` 
 */
@Serializable
data class InlineResponse4032ErrorsApiModel(
    @SerialName(value = "code")
    val code: kotlin.String? = null,
    @SerialName(value = "message")
    val message: kotlin.String? = null,
    @SerialName(value = "resource")
    val resource: kotlin.String? = null,
    @SerialName(value = "field")
    val `field`: kotlin.String? = null
) {

}

