/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*

/**
 * object containing information about the committer.
 * @param name The name of the author (or committer) of the commit
 * @param email The email of the author (or committer) of the commit
 */
@Serializable
data class ReposRepoNameContentsPathCommitter1ApiModel(
    /* The name of the author (or committer) of the commit */
    @SerialName(value = "name")
    val name: kotlin.String? = null,
    /* The email of the author (or committer) of the commit */
    @SerialName(value = "email")
    val email: kotlin.String? = null
) {

}

