/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models


import kotlinx.serialization.*

/**
 * 
 * @param path The relative path to the file that necessitates a review comment.
 * @param body Text of the review comment.
 * @param position The position in the diff where you want to add a review comment. Note this value is not the same as the line number in the file. For help finding the position value, read the note below.
 * @param line 
 * @param side 
 * @param startLine 
 * @param startSide 
 */
@Serializable
data class ReposOwnerRepoPullsPullNumberReviewsCommentsApiModel(
    /* The relative path to the file that necessitates a review comment. */
    @SerialName(value = "path")
    val path: kotlin.String,
    /* Text of the review comment. */
    @SerialName(value = "body")
    val body: kotlin.String,
    /* The position in the diff where you want to add a review comment. Note this value is not the same as the line number in the file. For help finding the position value, read the note below. */
    @SerialName(value = "position")
    val position: kotlin.Int? = null,
    @SerialName(value = "line")
    val line: kotlin.Int? = null,
    @SerialName(value = "side")
    val side: kotlin.String? = null,
    @SerialName(value = "start_line")
    val startLine: kotlin.Int? = null,
    @SerialName(value = "start_side")
    val startSide: kotlin.String? = null
) {

}

