/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package jp.co.yumemi.android.code_check.remote.models

import jp.co.yumemi.android.code_check.remote.models.LinkApiModel

import kotlinx.serialization.*

/**
 * 
 * @param self 
 * @param html 
 * @param pullRequest 
 */
@Serializable
data class ReviewCommentLinksApiModel(
    @SerialName(value = "self")
    val self: LinkApiModel,
    @SerialName(value = "html")
    val html: LinkApiModel,
    @SerialName(value = "pull_request")
    val pullRequest: LinkApiModel
) {

}

